version: '2'
services:
  ZOOKEEPER:
    image: wurstmeister/zookeeper:latest
    container_name: "ZOOKEEPER"
    ports:
      - "2181:2181"

  KAFKA_SSL:
    image: wurstmeister/kafka:latest
    container_name: "KAFKA_SSL"
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - ZOOKEEPER
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: "ZOOKEEPER:2181"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,SSL://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092,SSL://${KAFKA_ADVERTISED_HOST_NAME}:9093"
      KAFKA_SSL_KEYSTORE_LOCATION: "/var/private/ssl/kafka.server.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "changeit"
      KAFKA_SSL_KEY_PASSWORD: "changeit"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/var/private/ssl/kafka.server.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "changeit"
      KAFKA_CREATE_TOPICS: "testtopic:1:1"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_LEADER_REBALANCE_ENABLE: "false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/certs:/var/private/ssl



